// Code generated by "stringer -type=resolverType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[resolverDNS-0]
	_ = x[resolverManual-1]
}

const _resolverType_name = "resolverDNSresolverManual"

var _resolverType_index = [...]uint8{0, 11, 25}

func (i resolverType) String() string {
	if i < 0 || i >= resolverType(len(_resolverType_index)-1) {
		return "resolverType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _resolverType_name[_resolverType_index[i]:_resolverType_index[i+1]]
}
